# Generated by Django 3.1.3 on 2023-03-13 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(help_text='게시글의 제목을 한 줄로 작성하세요.', max_length=200, verbose_name='제목')),
                ('content', models.TextField(help_text='내용을 상세히 작성하세요.', verbose_name='내용')),
                ('create_date', models.DateTimeField(verbose_name='생성일')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('CK', 'Cook'), ('CT', 'Culture'), ('GA', 'Game'), ('LA', 'Language'), ('MU', 'Music'), ('OD', 'Outdoor'), ('SP', 'Sports')], max_length=10, null=True)),
                ('name', models.TextField(verbose_name='클럽이름')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('create_date', models.DateTimeField(verbose_name='생성일')),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.board')),
            ],
        ),
        migrations.AddField(
            model_name='board',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.club'),
        ),
    ]
