# Generated by Django 4.1.7 on 2023-03-08 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="board",
            name="author",
        ),
        migrations.RemoveField(
            model_name="board",
            name="like",
        ),
        migrations.RemoveField(
            model_name="club",
            name="owner",
        ),
        migrations.RemoveField(
            model_name="reply",
            name="author",
        ),
        migrations.RemoveField(
            model_name="reply",
            name="like",
        ),
        migrations.AddField(
            model_name="club",
            name="name",
            field=models.TextField(default=1, verbose_name="클럽이름"),
            preserve_default=False,
        ),
    ]
