# Generated by Django 4.1.7 on 2023-03-08 06:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_remove_board_author_remove_board_like_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reply",
            name="club_id",
        ),
        migrations.DeleteModel(
            name="Board",
        ),
        migrations.DeleteModel(
            name="Reply",
        ),
    ]
