# Generated by Django 4.1.7 on 2023-03-14 02:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_board_id_alter_club_id_alter_reply_id_clubpost"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="category",
        ),
        migrations.AddField(
            model_name="club",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="club",
            name="has_answer",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="club",
            name="name",
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
