# Generated by Django 4.1.7 on 2023-03-14 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_club_category_club_description_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="club",
            name="description",
        ),
        migrations.RemoveField(
            model_name="club",
            name="has_answer",
        ),
        migrations.AddField(
            model_name="club",
            name="category",
            field=models.CharField(
                choices=[
                    ("CK", "Cook"),
                    ("CT", "Culture"),
                    ("GA", "Game"),
                    ("LA", "Language"),
                    ("MU", "Music"),
                    ("OD", "Outdoor"),
                    ("SP", "Sports"),
                ],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="club",
            name="name",
            field=models.TextField(verbose_name="클럽이름"),
        ),
    ]
