# Generated by Django 4.1.7 on 2023-03-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_remove_reply_club_id_delete_board_delete_reply"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="category",
            field=models.CharField(
                choices=[("CK", "Cook"), ("CT", "Culture")], max_length=8
            ),
        ),
    ]
