# Generated by Django 4.1.7 on 2023-03-14 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_alter_board_id_alter_club_id_alter_reply_id"),
        ("main", "0004_remove_club_description_remove_club_has_answer_and_more"),
    ]

    operations = []
