# Generated by Django 4.1.7 on 2023-03-08 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_remove_club_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="category",
            field=models.CharField(
                choices=[("CT", "Culture"), ("CK", "Cook")], max_length=8, null=True
            ),
        ),
    ]
