# Generated by Django 4.1.7 on 2023-03-14 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0005_merge_20230314_1442"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
