# Generated by Django 4.1.7 on 2023-03-08 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_club_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="club",
            name="category",
            field=models.CharField(
                choices=[
                    ("CK", "Cook"),
                    ("CT", "Culture"),
                    ("GA", "Game"),
                    ("LA", "Language"),
                    ("MU", "Music"),
                    ("OD", "Outdoor"),
                    ("SP", "Sports"),
                ],
                max_length=10,
                null=True,
            ),
        ),
    ]
