# Generated by Django 4.1.7 on 2023-03-15 01:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0006_board_modify_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="author",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="reply",
            name="modify_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
