# Generated by Django 4.1.7 on 2023-03-09 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_club_category"),
    ]

    operations = [
        migrations.CreateModel(
            name="Board",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "subject",
                    models.CharField(
                        help_text="게시글의 제목을 한 줄로 작성하세요.",
                        max_length=200,
                        verbose_name="제목",
                    ),
                ),
                (
                    "content",
                    models.TextField(help_text="내용을 상세히 작성하세요.", verbose_name="내용"),
                ),
                ("create_date", models.DateTimeField(verbose_name="생성일")),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="main.club"
                    ),
                ),
            ],
        ),
    ]
