# Generated by Django 4.1.7 on 2023-03-15 02:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_board_author_reply_modify_date"),
        ("main", "0008_remove_board_author_remove_reply_author"),
    ]

    operations = []
