# Generated by Django 4.1.7 on 2023-03-15 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0009_merge_20230315_1142"),
        ("main", "0010_alter_board_author"),
    ]

    operations = []
