# Generated by Django 4.1.7 on 2023-03-15 05:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("main", "0011_merge_20230315_1400"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="voter",
            field=models.ManyToManyField(
                related_name="voter_board", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="board",
            name="author",
            field=models.ForeignKey(
                default=1,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="author_board",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
