# Generated by Django 4.1.7 on 2023-03-15 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0012_board_voter_alter_board_author"),
        ("main", "0012_reply_author"),
    ]

    operations = []
