# Generated by Django 4.1.7 on 2023-03-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0014_club_author"),
    ]

    operations = [
        migrations.AddField(
            model_name="board",
            name="event_date",
            field=models.DateField(default=1, verbose_name="모임일"),
            preserve_default=False,
        ),
    ]
