# Generated by Django 4.1.7 on 2023-03-16 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0015_board_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="board",
            name="event_date",
            field=models.DateField(null=True, verbose_name="모임일"),
        ),
    ]
